### PR TITLE
ir: thread parent BB and Function throughout

### PR DESCRIPTION
**Pull request by artagnon**
Alive IR suffers from the deficiency that the parent BasicBlock is not known in the Instr class, and the parent Function is not known in the BasicBlock class. The motivation for this patch is that, to support certain attributes like vscale, the dynamic vscale value (which will only be available on the function) needs to be known in the Instr class when checking programs with scalable vector types. The side-effect of this patch is that it cleans up the API of several dup() functions to be more intuitive.

### CODE REVIEW

**Comment by nunoplopes** [comment]
This patch increases memory consumption and the number of heap allocations for no good reason.

**Comment by artagnon** [comment]
> This patch increases memory consumption and the number of heap allocations for no good reason.

I tried my best to implement vscale_range without this patch, but it seems that the dynamic vscale value needs to be known, and it's only available on the Function: several functions in the VectorType require the dynamic vscale value to be passed for correctness. Kindly reconsider.

**Comment by artagnon** [comment]
> > This patch increases memory consumption and the number of heap allocations for no good reason.
> 
> I tried my best to implement vscale_range without this patch, but it seems that the dynamic vscale value needs to be known, and it's only available on the Function: several functions in the VectorType require the dynamic vscale value to be passed for correctness. Kindly reconsider.

For example, VectorType::getNumElements() will change depending on the dynamic vscale value. It is impossible for a VectorType to know the dynamic vscale value, because there is no Function associated with it. The alternative to this patch is to get the vscale value from the Function associated with the State and pass it around everywhere, but I don't know if that's much better than this patch in terms of memory consumption.

**Comment by nunoplopes** [comment]
Isn't the dynamic vscale an SMT variable? If so, it's parte of the state, not part of the IR.

**Comment by artagnon** [comment]
> Isn't the dynamic vscale an SMT variable? If so, it's parte of the state, not part of the IR.

Thanks for the guidance; I will make it part of the State.

**Pull request closed without merging**
