### PR TITLE
{u,s}{min,max}, abs intrinsics modelling

### PR DESCRIPTION
**Pull request by LebedevRI**
RFC: https://lists.llvm.org/pipermail/llvm-dev/2020-June/142257.html
LangRef patch: https://reviews.llvm.org/D81829 

CC @rotateright @nikic

### CODE REVIEW

**Comment by LebedevRI** [comment]
@nunoplopes Ship it!

**Comment by LebedevRI** [comment]
Seeing how there hasn't been any new commits to the repo in last few weeks,
and no new (public) activity in last few weeks at https://github.com/nunoplopes,
does anyone else have a commit access here, or is the bus factor at one here?
@regehr

**Comment by regehr** [comment]
I do not have commit access! it's possible Nuno is on vacation

**Comment by aqjune** [comment]
I just saw the comment! I don't have commit access either.

**Comment by nunoplopes** [comment]
Sorry, I was offline on vacation. Just came back and catching up.

**Comment by LebedevRI** [comment]
Thanks. Unless the current situation is intentional, it might be good to improve it..

**Pull request merged**
