### PR TITLE
clang plugin: add -tv-batch to verify optimizations in a batch

### PR DESCRIPTION
**Pull request by aqjune**
This is a patch that adds `-tv-batch` for clang plugin that batches supported optimizations and verify them at once.

Currently WIP; running benchmarks to see whether it works successfully

### CODE REVIEW

**Comment by aqjune** [comment]
Closing this, since this won't be used for the experiment.

**Comment by nunoplopes** [comment]
But is the patch close to being finished?
This is still a nice feature to have. We can finish it later. Just wondering if the patch is worth it keeping for later or if the approach doesn't work at all?

**Comment by aqjune** [comment]
Um, I guess this patch might be still slightly far from being prepared due to the function duplication issue - #522 .
Function duplication now isn't an urgent issue because bitcodes are pre-generated and alive-tv process is created per function pairs. So maybe it can be done after the submission..? :) Then, this can be reopened.

**Comment by aqjune** [comment]
I'll revive this patch after the deadline.

**Pull request closed without merging**
