### PR TITLE
Try to cleanup CMake a bit

### PR DESCRIPTION
**Pull request by LebedevRI**
As disscussed in https://github.com/AliveToolkit/alive2/pull/89
the current linking/dependency handling is a bit of a mess.

Even though there is alive2 library being built from smaller static libs,
the executables don't actually link to it, but to those static libs,
which e.g. pessimizes LTO.

Also, even though a very recent CMake version is required,
the library dependency handling was still using prehistoric method
of variables instead of imported targets.

So i've tried to clean things up a bit:
* include/link Z3 / llvm PRIVATE'ly to the most fine-grained build target
* link our internal libs PUBLIC'ly into alive2 library
* don't link our internal libs into binaries
* link alive2 lib PRIVATE'ly into binaries

### CODE REVIEW

**Comment by LebedevRI** [comment]
Full disclaimer: i have only checked tv-less linux build. I have not checked tv build, i have not checked other oses, cygwin.

@aqjune could you please try this patch? Does it fix the issue you were observing?

**Comment by LebedevRI** [comment]
Thanks for taking a look!
Duh, try now please.

**Comment by nunoplopes** [comment]
It's failing on my CentOS VM:
```
FAILED: CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o
/opt/rh/devtoolset-8/root/usr/bin/c++   -I../ -isystem /home/nuno/llvm/llvm/include -isystem /home/nuno/llvm/build/include -Wall -march=native -fPIC  -Werror -g -Og -g   "-D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -std=gnu++17 -MD -MT CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o -c ../llvm_util/utils.cpp
<command-line>: error: "_GNU_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
```

**Comment by nunoplopes** [comment]
never mind, the error goes away with a clean build.  alive-tv doesn't link though. The command line looks very suspicious: `CMakeFiles/alive-tv.dir/tools/alive-tv.cpp.o -o alive-tv ... libalive2.so libir.a libsmt.a libtools.a libutil.a libllvm_util.a ...`

**Comment by LebedevRI** [comment]
Pushed suspected fixes, could you _please_ retry with empty (`rm -rf build`) build dir?

**Comment by nunoplopes** [comment]
> Pushed suspected fixes, could you please retry with empty (rm -rf build) build dir?

Sorry, still not linking `alive-tv`. The opt plugin is fine (in the tv directory). `libalive2.so` is empty though; no symbols.

**Comment by LebedevRI** [comment]
> `libalive2.so` is empty though; no symbols.

That might be ok, if `-DBUILD_SHARED_LIBS=OFF`.

> Sorry, still not linking `alive-tv`.

Oh, `alive-tv`, not `tv` plugin.
Could you please quote the build output?

**Comment by nunoplopes** [comment]
> libalive2.so is empty though; no symbols.
> 
> That might be ok, if -DBUILD_SHARED_LIBS=OFF.

I'm using: `cmake -GNinja -DLLVM_DIR=~/llvm/build/lib/cmake/llvm -DBUILD_TV=1 -DCMAKE_BUILD_TYPE=Release ..`

> Oh, alive-tv, not tv plugin.
> Could you please quote the build output?

```
]$ ninja
[23/34] Building CXX object tv/CMakeFiles/tv.dir/tv.cpp.o
<command-line>: warning: "_GNU_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
[24/34] Building CXX object CMakeFiles/alive-tv.dir/tools/alive-tv.cpp.o
<command-line>: warning: "_GNU_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
[25/34] Building CXX object CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o
<command-line>: warning: "_GNU_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
[29/34] Linking CXX executable alive-tv
FAILED: alive-tv
: && /opt/rh/devtoolset-8/root/usr/bin/c++  -Wall -march=native -fPIC  -O3 -DNDEBUG -O2 -DNDEBUG  -Wl,-rpath-link,  -Wl,-O3 -Wl,--gc-sections CMakeFiles/alive-tv.dir/tools/alive-tv.cpp.o  -o alive-tv  -Wl,-rpath,"\$ORIGIN/../lib:/home/nuno/llvm/build/./lib" -lpthread libalive2.so libir.a libsmt.a libtools.a libutil.a libllvm_util.a /home/nuno/llvm/build/lib/libLLVMIRReader.a /home/nuno/llvm/build/lib/libLLVMAsmParser.a /home/nuno/llvm/build/lib/libLLVMBitReader.a /home/nuno/llvm/build/lib/libLLVMCore.a /home/nuno/llvm/build/lib/libLLVMBinaryFormat.a /home/nuno/llvm/build/lib/libLLVMRemarks.a /home/nuno/llvm/build/lib/libLLVMBitstreamReader.a /home/nuno/llvm/build/lib/libLLVMSupport.a -lrt -ldl -lpthread -lm /usr/lib/libz3.so /home/nuno/llvm/build/lib/libLLVMDemangle.a && :
libtools.a(transform.cpp.o): In function `tools::TransformVerify::fixupTypes(tools::TypingAssignments const&)':
transform.cpp:(.text+0x358): undefined reference to `IR::Function::fixupTypes(smt::Model const&)'
libtools.a(transform.cpp.o): In function `tools::Transform::print(std::ostream&, tools::TransformPrintOpts const&) const':
transform.cpp:(.text+0x3bc): undefined reference to `IR::Function::print(std::ostream&, bool) const'
....
```

Thanks!

**Comment by nunoplopes** [comment]
The cmd line for libalive2.so looks reasonable to me:
```
&& /opt/rh/devtoolset-8/root/usr/bin/c++ -fPIC -Wall -march=native -fPIC  -O3 -DNDEBUG -O2 -DNDEBUG   -shared -Wl,-soname,libalive2.so -o libalive2.so   libir.a libsmt.a libtools.a libutil.a libllvm_util.a /home/nuno/llvm/build/lib/libLLVMIRReader.a /home/nuno/llvm/build/lib/libLLVMAsmParser.a /home/nuno/llvm/build/lib/libLLVMBitReader.a /home/nuno/llvm/build/lib/libLLVMCore.a /home/nuno/llvm/build/lib/libLLVMBinaryFormat.a /home/nuno/llvm/build/lib/libLLVMRemarks.a /home/nuno/llvm/build/lib/libLLVMBitstreamReader.a /home/nuno/llvm/build/lib/libLLVMSupport.a -lrt -ldl -lpthread -lm /usr/lib/libz3.so /home/nuno/llvm/build/lib/libLLVMDemangle.a && :
```

**Comment by LebedevRI** [comment]
Hold on, that failure looks trivial...

**Comment by nunoplopes** [comment]
Thanks! It's working now with a further tweak:
```target_link_libraries(llvm_util PRIVATE ir)```

However, I'm not a fan of this change. I prefer to link statically than dynamically since it's much easier to move binaries around without worrying about dependencies. Especially true for the opt's tv.so plugin. Also, right now it is linking everything statically *and* keeping the link to libalive2.so. Strange.
Anyway, libalive2.so was added mostly for Souper to link with Alive2, not for internal consumption,

**Comment by LebedevRI** [comment]
> Thanks! It's working now with a further tweak:
> `target_link_libraries(llvm_util PRIVATE ir)`

Ah, i guess i'm not seeing that due to not building TV, which results
in that code being dropped way before it causes missing linking deps.

> However, I'm not a fan of this change.

> I prefer to link statically than dynamically since it's much easier to move binaries around without worrying about dependencies. Especially true for the opt's tv.so plugin.

I agree with that, if possible static linking is good.
I didn't mean to actually shoe-horn `-DBUILD_SHARED_LIBS=ON` default; changed, thanks.

> Also, right now it is linking everything statically _and_ keeping the link to libalive2.so. Strange.

This is kind-of intentional, not doing this abstraction results in more bug potential,
as it was seen in #89.

> Anyway, libalive2.so was added mostly for Souper to link with Alive2, not for internal consumption,

**Comment by LebedevRI** [comment]
Great point! I thin this will "accidentally" address @nunoplopes complaint too - this way there won't be alive2 that we'll link against unless the shared library was really actually requested.

**Comment by LebedevRI** [comment]
@aqjune does it work for you now?

**Comment by aqjune** [comment]
I didn't realize that the last commit was addressing the problem.
Yes, it works. Thanks.

**Comment by nunoplopes** [comment]
I've tested the patch and I can see that the CFLAGS are being overridden (perhaps with the LLVM ones?).
Also, the alive binary is being linked with the LLVM, and it doesn't need any of that.

The debug build fails for me with:
```
FAILED: CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o
c++   -I../ -isystem /home/nuno/llvm/llvm/include -isystem /home/nuno/llvm/build/include -Wall -march=native -fPIC  -Werror -g -Og -g   "-D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -std=gnu++17 -MD -MT CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/utils.cpp.o -c ../llvm_util/utils.cpp
<command-line>: error: "_GNU_SOURCE" redefined [-Werror]
<command-line>: note: this is the location of the previous definition
```

**Comment by LebedevRI** [comment]
Sorry, this got stale.

**Pull request closed without merging**
